#!/bin/bash

ipfs init
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin "[\"https://ipfs.swarm.city\"]"
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Credentials "[\"true\"]"
ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods "[\"PUT\", \"POST\", \"GET\"]"

touch /root/.jsawkrc && npm install -g jsawk

cat ~/.ipfs/config | jsawk 'return this.Identity'

ipfs daemon &

node proxylistener.js
